insert into product (id, name, price) values (1, 'Sobe - Berry Energy', 24.96);
insert into product (id, name, price) values (2, 'Bread - Raisin', 77.13);
insert into product (id, name, price) values (3, 'Lettuce - Romaine, Heart', 87.49);
insert into product (id, name, price) values (4, 'Salt - Seasoned', 61.85);
insert into product (id, name, price) values (5, 'Foil - 4oz Custard Cup', 30.66);
insert into product (id, name, price) values (6, 'Hummus - Spread', 4.15);
insert into product (id, name, price) values (7, 'Salmon - Atlantic, Skin On', 84.18);
insert into product (id, name, price) values (8, 'Gatorade - Orange', 27.59);
insert into product (id, name, price) values (9, 'True - Vue Containers', 57.57);
insert into product (id, name, price) values (10, 'Muffin - Mix - Mango Sour Cherry', 68.27);
insert into product (id, name, price) values (11, 'Fond - Chocolate', 31.96);
insert into product (id, name, price) values (12, 'Cheese - Brie, Triple Creme', 94.21);
insert into product (id, name, price) values (13, 'Ecolab - Medallion', 51.9);
insert into product (id, name, price) values (14, 'Muffin Mix - Corn Harvest', 42.27);
insert into product (id, name, price) values (15, 'Muffin Mix - Lemon Cranberry', 27.73);
insert into product (id, name, price) values (16, 'Seedlings - Clamshell', 92.9);
insert into product (id, name, price) values (17, 'Cocoa Powder - Natural', 81.57);
insert into product (id, name, price) values (18, 'Wiberg Super Cure', 54.74);
insert into product (id, name, price) values (19, 'Bagel - Sesame Seed Presliced', 61.66);
insert into product (id, name, price) values (20, 'Oil - Avocado', 49.85);
insert into product (id, name, price) values (21, 'Milkettes - 2%', 97.12);
insert into product (id, name, price) values (22, 'Muffin - Blueberry Individual', 90.57);
insert into product (id, name, price) values (23, 'Skirt - 24 Foot', 83.99);
insert into product (id, name, price) values (24, 'Rice Paper', 9.94);
insert into product (id, name, price) values (25, 'Chinese Foods - Plain Fried Rice', 48.03);
insert into product (id, name, price) values (26, 'Berry Brulee', 54.77);
insert into product (id, name, price) values (27, 'Soda Water - Club Soda, 355 Ml', 32.36);
insert into product (id, name, price) values (28, 'Peas - Frozen', 22.25);
insert into product (id, name, price) values (29, 'Cauliflower', 36.29);
insert into product (id, name, price) values (30, 'Aspic - Clear', 36.3);
insert into product (id, name, price) values (31, 'Pepper - Cubanelle', 20.87);
insert into product (id, name, price) values (32, 'Isomalt', 94.46);
insert into product (id, name, price) values (33, 'Pork - Bacon, Sliced', 2.95);
insert into product (id, name, price) values (34, 'Coconut - Whole', 23.89);
insert into product (id, name, price) values (35, 'Flavouring - Rum', 15.14);
insert into product (id, name, price) values (36, 'Arctic Char - Fillets', 14.09);
insert into product (id, name, price) values (37, 'Wine - White, Lindemans Bin 95', 97.17);
insert into product (id, name, price) values (38, 'Liquid Aminios Acid - Braggs', 3.61);
insert into product (id, name, price) values (39, 'Yogurt - Strawberry, 175 Gr', 16.06);
insert into product (id, name, price) values (40, 'Yogurt - Strawberry, 175 Gr', 73.94);
insert into product (id, name, price) values (41, 'Mushroom - Morel Frozen', 90.85);
insert into product (id, name, price) values (42, 'Tilapia - Fillets', 86.84);
insert into product (id, name, price) values (43, 'Bread Sour Rolls', 27.37);
insert into product (id, name, price) values (44, 'Ecolab Silver Fusion', 33.33);
insert into product (id, name, price) values (45, 'Pears - Bosc', 43.53);
insert into product (id, name, price) values (46, 'Pie Shells 10', 39.16);
insert into product (id, name, price) values (47, 'Cookies - Oreo, 4 Pack', 42.21);
insert into product (id, name, price) values (48, 'Crab Brie In Phyllo', 58.81);
insert into product (id, name, price) values (49, 'Puree - Guava', 81.74);
insert into product (id, name, price) values (50, 'Cabbage Roll', 59.62);
insert into product (id, name, price) values (51, 'Goulash Seasoning', 62.7);
insert into product (id, name, price) values (52, 'Chocolate Bar - Reese Pieces', 31.18);
insert into product (id, name, price) values (53, 'Garlic - Peeled', 66.13);
insert into product (id, name, price) values (54, 'Onions - Cooking', 92.32);
insert into product (id, name, price) values (55, 'Flavouring Vanilla Artificial', 4.31);
insert into product (id, name, price) values (56, 'Cabbage Roll', 56.91);
insert into product (id, name, price) values (57, 'Pepper - Cayenne', 94.32);
insert into product (id, name, price) values (58, 'Table Cloth 62x120 White', 89.68);
insert into product (id, name, price) values (59, 'Oil - Shortening,liqud, Fry', 3.84);
insert into product (id, name, price) values (60, 'Oil - Pumpkinseed', 71.64);
insert into product (id, name, price) values (61, 'Pastrami', 55.02);
insert into product (id, name, price) values (62, 'Radish - Black, Winter, Organic', 60.43);
insert into product (id, name, price) values (63, 'Beer - Upper Canada Light', 27.21);
insert into product (id, name, price) values (64, 'Soup Campbells - Tomato Bisque', 75.47);
insert into product (id, name, price) values (65, 'Cookie Dough - Peanut Butter', 80.54);
insert into product (id, name, price) values (66, 'Shichimi Togarashi Peppeers', 18.74);
insert into product (id, name, price) values (67, 'Sauce - Caesar Dressing', 23.36);
insert into product (id, name, price) values (68, 'Nantucket - Orange Mango Cktl', 75.86);
insert into product (id, name, price) values (69, 'Cup - Translucent 7 Oz Clear', 87.67);
insert into product (id, name, price) values (70, 'Squash - Sunburst', 30.72);
insert into product (id, name, price) values (71, 'Mountain Dew', 87.96);
insert into product (id, name, price) values (72, 'Bar Mix - Pina Colada, 355 Ml', 52.14);
insert into product (id, name, price) values (73, 'Squash - Sunburst', 2.53);
insert into product (id, name, price) values (74, 'Cheese - Woolwich Goat, Log', 89.44);
insert into product (id, name, price) values (75, 'Pork - Ham Hocks - Smoked', 68.3);
insert into product (id, name, price) values (76, 'Squid Ink', 30.25);
insert into product (id, name, price) values (77, 'Sprouts - Onion', 14.35);
insert into product (id, name, price) values (78, 'Carrots - Purple, Organic', 34.77);
insert into product (id, name, price) values (79, 'Island Oasis - Strawberry', 86.54);
insert into product (id, name, price) values (80, 'Shallots', 54.55);
insert into product (id, name, price) values (81, 'Mix Pina Colada', 90.2);
insert into product (id, name, price) values (82, 'Pie Filling - Pumpkin', 83.42);
insert into product (id, name, price) values (83, 'Milk - Chocolate 250 Ml', 18.83);
insert into product (id, name, price) values (84, 'Beef - Tenderlion, Center Cut', 10.74);
insert into product (id, name, price) values (85, 'Longos - Grilled Salmon With Bbq', 39.61);
insert into product (id, name, price) values (86, 'Beef - Diced', 52.37);
insert into product (id, name, price) values (87, 'Piping Jelly - All Colours', 70.33);
insert into product (id, name, price) values (88, 'Pastry - Key Limepoppy Seed Tea', 52.87);
insert into product (id, name, price) values (89, 'Watercress', 64.43);
insert into product (id, name, price) values (90, 'Soup Knorr Chili With Beans', 60.75);
insert into product (id, name, price) values (91, 'Heavy Duty Dust Pan', 45.98);
insert into product (id, name, price) values (92, 'Snapple Lemon Tea', 40.17);
insert into product (id, name, price) values (93, 'Pepper - Julienne, Frozen', 97.17);
insert into product (id, name, price) values (94, 'Jameson Irish Whiskey', 39.42);
insert into product (id, name, price) values (95, 'Dome Lid Clear P92008h', 24.07);
insert into product (id, name, price) values (96, 'Soup - Knorr, Ministrone', 43.45);
insert into product (id, name, price) values (97, 'Tomato - Plum With Basil', 70.32);
insert into product (id, name, price) values (98, 'Mousse - Banana Chocolate', 67.41);
insert into product (id, name, price) values (99, 'Pasta - Lasagne, Fresh', 17.94);
insert into product (id, name, price) values (100, 'Snapple Lemon Tea', 28.72);
insert into product (id, name, price) values (101, 'Sauce - Gravy, Au Jus, Mix', 3.01);
insert into product (id, name, price) values (102, 'Pastry - Chocolate Chip Muffin', 50.16);
insert into product (id, name, price) values (103, 'Napkin White', 45.07);
insert into product (id, name, price) values (104, 'Tendrils - Baby Pea, Organic', 8.36);
insert into product (id, name, price) values (105, 'Pepper - Red Chili', 24.61);
insert into product (id, name, price) values (106, 'Skirt - 24 Foot', 36.11);
insert into product (id, name, price) values (107, 'Truffle Cups - White Paper', 96.96);
insert into product (id, name, price) values (108, 'Flour - Whole Wheat', 98.81);
insert into product (id, name, price) values (109, 'Pickle - Dill', 63.0);
insert into product (id, name, price) values (110, 'Lettuce - Escarole', 81.92);
insert into product (id, name, price) values (111, 'Cheese - Bakers Cream Cheese', 91.93);
insert into product (id, name, price) values (112, 'Longos - Grilled Veg Sandwiches', 31.23);
insert into product (id, name, price) values (113, 'Stock - Chicken, White', 68.8);
insert into product (id, name, price) values (114, 'Nestea - Iced Tea', 36.01);
insert into product (id, name, price) values (115, 'Cake Sheet Combo Party Pack', 77.1);
insert into product (id, name, price) values (116, 'Milk - Homo', 90.75);
insert into product (id, name, price) values (117, 'Instant Coffee', 63.52);
insert into product (id, name, price) values (118, 'Piping - Bags Quizna', 35.73);
insert into product (id, name, price) values (119, 'Cheese Cheddar Processed', 58.24);
insert into product (id, name, price) values (120, 'Chilli Paste, Hot Sambal Oelek', 41.3);
insert into product (id, name, price) values (121, 'Bar Nature Valley', 9.16);
insert into product (id, name, price) values (122, 'Shrimp, Dried, Small / Lb', 66.08);
insert into product (id, name, price) values (123, 'Soup Campbells - Italian Wedding', 43.47);
insert into product (id, name, price) values (124, 'Sauce - Fish 25 Ozf Bottle', 49.75);
insert into product (id, name, price) values (125, 'Melon - Honey Dew', 70.48);
insert into product (id, name, price) values (126, 'Seedlings - Mix, Organic', 19.25);
insert into product (id, name, price) values (127, 'Lobster - Tail, 3 - 4 Oz', 82.21);
insert into product (id, name, price) values (128, 'Muffin - Mix - Creme Brule 15l', 1.21);
insert into product (id, name, price) values (129, 'Cardamon Seed / Pod', 8.15);
insert into product (id, name, price) values (130, 'Wine - Cousino Macul Antiguas', 1.23);
insert into product (id, name, price) values (131, 'Tea - Camomele', 14.44);
insert into product (id, name, price) values (132, 'Schnappes - Peach, Walkers', 88.77);
insert into product (id, name, price) values (133, 'Kiwi', 98.28);
insert into product (id, name, price) values (134, 'Sugar - Brown, Individual', 46.23);
insert into product (id, name, price) values (135, 'Tea - Herbal Orange Spice', 43.54);
insert into product (id, name, price) values (136, 'Appetizer - Smoked Salmon / Dill', 63.75);
insert into product (id, name, price) values (137, 'Beans - Butter Lrg Lima', 46.0);
insert into product (id, name, price) values (138, 'Wine - Magnotta, Merlot Sr Vqa', 95.77);
insert into product (id, name, price) values (139, 'Lotus Leaves', 54.44);
insert into product (id, name, price) values (140, 'Wine - Chianti Classica Docg', 24.34);
insert into product (id, name, price) values (141, 'Wine - Guy Sage Touraine', 42.03);
insert into product (id, name, price) values (142, 'Venison - Racks Frenched', 34.4);
insert into product (id, name, price) values (143, 'French Kiss Vanilla', 58.56);
insert into product (id, name, price) values (144, 'Soup - Campbells', 34.72);
insert into product (id, name, price) values (145, 'Iced Tea - Lemon, 460 Ml', 28.1);
insert into product (id, name, price) values (146, 'Beer - Fruli', 28.7);
insert into product (id, name, price) values (147, 'Duck - Legs', 33.92);
insert into product (id, name, price) values (148, 'Crush - Grape, 355 Ml', 39.31);
insert into product (id, name, price) values (149, 'Yucca', 65.81);
insert into product (id, name, price) values (150, 'Cheese - Roquefort Pappillon', 47.0);
insert into product (id, name, price) values (151, 'Lid Coffeecup 12oz D9542b', 20.68);
insert into product (id, name, price) values (152, 'Bread - Raisin', 7.3);
insert into product (id, name, price) values (153, 'Juice - Apple, 1.36l', 34.18);
insert into product (id, name, price) values (154, 'Ice Cream - Fudge Bars', 87.55);
insert into product (id, name, price) values (155, 'Beans - Green', 40.9);
insert into product (id, name, price) values (156, 'Bacardi Breezer - Strawberry', 46.22);
insert into product (id, name, price) values (157, 'Marjoram - Dried, Rubbed', 20.35);
insert into product (id, name, price) values (158, 'Bread Base - Goodhearth', 62.42);
insert into product (id, name, price) values (159, 'Wine - Rosso Del Veronese Igt', 19.85);
insert into product (id, name, price) values (160, 'Sauce - Salsa', 33.11);
insert into product (id, name, price) values (161, 'Boogies', 40.19);
insert into product (id, name, price) values (162, 'Jolt Cola - Electric Blue', 70.8);
insert into product (id, name, price) values (163, 'Pasta - Spaghetti, Dry', 98.3);
insert into product (id, name, price) values (164, 'Grapefruit - White', 22.67);
insert into product (id, name, price) values (165, 'Rum - Cream, Amarula', 53.93);
insert into product (id, name, price) values (166, 'Soup - Campbells, Chix Gumbo', 15.26);
insert into product (id, name, price) values (167, 'Salmon Atl.whole 8 - 10 Lb', 55.36);
insert into product (id, name, price) values (168, 'Cheese - Cheddar, Medium', 58.17);
insert into product (id, name, price) values (169, 'Beef Flat Iron Steak', 61.68);
insert into product (id, name, price) values (170, 'Carbonated Water - Strawberry', 60.12);
insert into product (id, name, price) values (171, 'Poppy Seed', 74.47);
insert into product (id, name, price) values (172, 'Chips - Doritos', 69.46);
insert into product (id, name, price) values (173, 'Lamb - Racks, Frenched', 83.93);
insert into product (id, name, price) values (174, 'Sprouts - China Rose', 33.65);
insert into product (id, name, price) values (175, 'Wine - Rubyport', 38.43);
insert into product (id, name, price) values (176, 'Sole - Iqf', 28.71);
insert into product (id, name, price) values (177, 'Okra', 86.29);
insert into product (id, name, price) values (178, 'Tea - Camomele', 48.51);
insert into product (id, name, price) values (179, 'Salmon - Smoked, Sliced', 5.95);
insert into product (id, name, price) values (180, 'Honey - Liquid', 50.21);
insert into product (id, name, price) values (181, 'Bag - Clear 7 Lb', 75.74);
insert into product (id, name, price) values (182, 'Chicken - Whole Fryers', 86.51);
insert into product (id, name, price) values (183, 'Trout - Smoked', 43.41);
insert into product (id, name, price) values (184, 'Puree - Raspberry', 55.34);
insert into product (id, name, price) values (185, 'Fenngreek Seed', 83.62);
insert into product (id, name, price) values (186, 'V8 Splash Strawberry Kiwi', 39.31);
insert into product (id, name, price) values (187, 'Onions - Red Pearl', 42.8);
insert into product (id, name, price) values (188, 'Cheese - Havarti, Roasted Garlic', 91.97);
insert into product (id, name, price) values (189, 'Glass Clear 8 Oz', 73.15);
insert into product (id, name, price) values (190, 'Otomegusa Dashi Konbu', 19.92);
insert into product (id, name, price) values (191, 'Cheese - Cheddar With Claret', 82.34);
insert into product (id, name, price) values (192, 'Ice Cream Bar - Hageen Daz To', 27.17);
insert into product (id, name, price) values (193, 'Wine - Red, Antinori Santa', 44.06);
insert into product (id, name, price) values (194, 'Veal - Leg', 91.21);
insert into product (id, name, price) values (195, 'Veal - Striploin', 4.69);
insert into product (id, name, price) values (196, 'Muffin - Mix - Mango Sour Cherry', 23.62);
insert into product (id, name, price) values (197, 'Chocolate Liqueur - Godet White', 38.42);
insert into product (id, name, price) values (198, 'Turkey - Breast, Bone - In', 82.4);
insert into product (id, name, price) values (199, 'Soup - Campbells, Butternut', 67.17);
insert into product (id, name, price) values (200, 'Nutmeg - Ground', 88.86);
insert into product (id, name, price) values (201, 'Wine - Chianti Classica Docg', 55.58);
insert into product (id, name, price) values (202, 'Wine - Stoneliegh Sauvignon', 74.11);
insert into product (id, name, price) values (203, 'Trout Rainbow Whole', 37.44);
insert into product (id, name, price) values (204, 'Bread - Raisin', 25.56);
insert into product (id, name, price) values (205, 'Pie Shell - 9', 98.57);
insert into product (id, name, price) values (206, 'Beef - Roasted, Cooked', 12.23);
insert into product (id, name, price) values (207, 'Lettuce - Arugula', 50.05);
insert into product (id, name, price) values (208, 'Plate Pie Foil', 69.02);
insert into product (id, name, price) values (209, 'Turkey - Whole, Fresh', 88.36);
insert into product (id, name, price) values (210, 'Juice - Tomato, 48 Oz', 73.93);
insert into product (id, name, price) values (211, 'Soup - Canadian Pea, Dry Mix', 61.35);
insert into product (id, name, price) values (212, 'Squash - Guords', 17.75);
insert into product (id, name, price) values (213, 'Beans - Fava Fresh', 33.27);
insert into product (id, name, price) values (214, 'Apples - Sliced / Wedge', 52.01);
insert into product (id, name, price) values (215, 'Napkin - Dinner, White', 30.15);
insert into product (id, name, price) values (216, 'Mushrooms - Honey', 40.64);
insert into product (id, name, price) values (217, 'Rosemary - Dry', 15.2);
insert into product (id, name, price) values (218, 'Calypso - Pineapple Passion', 52.95);
insert into product (id, name, price) values (219, 'Dip - Tapenade', 93.83);
insert into product (id, name, price) values (220, 'Container - Clear 32 Oz', 67.05);
insert into product (id, name, price) values (221, 'Glucose', 54.22);
insert into product (id, name, price) values (222, 'Cherries - Maraschino,jar', 43.18);
insert into product (id, name, price) values (223, 'Swiss Chard - Red', 27.42);
insert into product (id, name, price) values (224, 'Chilli Paste, Hot Sambal Oelek', 90.29);
insert into product (id, name, price) values (225, 'Lamb - Whole Head Off', 73.7);
insert into product (id, name, price) values (226, 'Radish - Pickled', 17.02);
insert into product (id, name, price) values (227, 'Wine - Mas Chicet Rose, Vintage', 44.93);
insert into product (id, name, price) values (228, 'Shrimp - Prawn', 95.59);
insert into product (id, name, price) values (229, 'Lettuce - Curly Endive', 29.26);
insert into product (id, name, price) values (230, 'Tomato - Green', 41.61);
insert into product (id, name, price) values (231, 'Cod - Fillets', 68.93);
insert into product (id, name, price) values (232, 'Cleaner - Bleach', 39.44);
insert into product (id, name, price) values (233, 'Turnip - Mini', 62.25);
insert into product (id, name, price) values (234, 'Rum - Dark, Bacardi, Black', 51.78);
insert into product (id, name, price) values (235, 'Pork - Tenderloin, Frozen', 66.44);
insert into product (id, name, price) values (236, 'Cheese - Ermite Bleu', 95.44);
insert into product (id, name, price) values (237, 'Salt - Seasoned', 62.52);
insert into product (id, name, price) values (238, 'Nestea - Iced Tea', 23.62);
insert into product (id, name, price) values (239, 'Quiche Assorted', 24.61);
insert into product (id, name, price) values (240, 'Truffle Cups - Brown', 21.15);
insert into product (id, name, price) values (241, 'Sour Puss - Tangerine', 98.27);
insert into product (id, name, price) values (242, 'Cocoa Butter', 75.12);
insert into product (id, name, price) values (243, 'Cheese - Parmesan Grated', 61.6);
insert into product (id, name, price) values (244, 'Wine - Placido Pinot Grigo', 5.15);
insert into product (id, name, price) values (245, 'Lobster - Baby, Boiled', 48.66);
insert into product (id, name, price) values (246, 'Cherries - Bing, Canned', 15.24);
insert into product (id, name, price) values (247, 'Sultanas', 85.28);
insert into product (id, name, price) values (248, 'Wonton Wrappers', 14.33);
insert into product (id, name, price) values (249, 'Pork - Bacon Cooked Slcd', 77.95);
insert into product (id, name, price) values (250, 'Coconut - Whole', 3.14);
insert into product (id, name, price) values (251, 'Fond - Chocolate', 6.14);
insert into product (id, name, price) values (252, 'Tomato Paste', 34.74);
insert into product (id, name, price) values (253, 'Beef - Tongue, Cooked', 38.24);
insert into product (id, name, price) values (254, 'Cattail Hearts', 73.38);
insert into product (id, name, price) values (255, 'Milk - Chocolate 500ml', 22.71);
insert into product (id, name, price) values (256, 'Banana - Leaves', 98.28);
insert into product (id, name, price) values (257, 'Beer - Fruli', 17.23);
insert into product (id, name, price) values (258, 'V8 - Tropical Blend', 82.67);
insert into product (id, name, price) values (259, 'Tea - Orange Pekoe', 80.97);
insert into product (id, name, price) values (260, 'Hot Choc Vending', 21.6);
insert into product (id, name, price) values (261, 'Pastry - Baked Scones - Mini', 87.83);
insert into product (id, name, price) values (262, 'Veal Inside - Provimi', 22.77);
insert into product (id, name, price) values (263, 'Chicken - Thigh, Bone In', 94.67);
insert into product (id, name, price) values (264, 'Pie Box - Cello Window 2.5', 91.47);
insert into product (id, name, price) values (265, 'Chips Potato All Dressed - 43g', 7.24);
insert into product (id, name, price) values (266, 'Oil - Coconut', 21.1);
insert into product (id, name, price) values (267, 'Rabbit - Legs', 91.96);
insert into product (id, name, price) values (268, 'Compound - Passion Fruit', 21.9);
insert into product (id, name, price) values (269, 'Cocoa Powder - Dutched', 50.1);
insert into product (id, name, price) values (270, 'Wine - Saint - Bris 2002, Sauv', 63.69);
insert into product (id, name, price) values (271, 'Pasta - Fettuccine, Egg, Fresh', 25.5);
insert into product (id, name, price) values (272, 'Ecolab - Hand Soap Form Antibac', 46.52);
insert into product (id, name, price) values (273, 'Beer - Camerons Cream Ale', 38.63);
insert into product (id, name, price) values (274, 'Pesto - Primerba, Paste', 5.61);
insert into product (id, name, price) values (275, 'Coffee - Ristretto Coffee Capsule', 96.95);
insert into product (id, name, price) values (276, 'Radish', 24.24);
insert into product (id, name, price) values (277, 'Chocolate - Unsweetened', 94.99);
insert into product (id, name, price) values (278, 'Bread - Triangle White', 22.78);
insert into product (id, name, price) values (279, 'Sausage - Liver', 33.99);
insert into product (id, name, price) values (280, 'Appetizer - Smoked Salmon / Dill', 77.72);
insert into product (id, name, price) values (281, 'Tart Shells - Savory, 4', 4.84);
insert into product (id, name, price) values (282, 'Ginger - Crystalized', 18.62);
insert into product (id, name, price) values (283, 'Sauce Bbq Smokey', 56.95);
insert into product (id, name, price) values (284, 'Hand Towel', 25.66);
insert into product (id, name, price) values (285, 'Sauce - Roasted Red Pepper', 10.02);
insert into product (id, name, price) values (286, 'Fish - Halibut, Cold Smoked', 8.4);
insert into product (id, name, price) values (287, 'Tomatoes Tear Drop Yellow', 41.16);
insert into product (id, name, price) values (288, 'Food Colouring - Orange', 17.08);
insert into product (id, name, price) values (289, 'Cognac - Courvaisier', 81.06);
insert into product (id, name, price) values (290, 'Samosa - Veg', 40.01);
insert into product (id, name, price) values (291, 'Dome Lid Clear P92008h', 19.88);
insert into product (id, name, price) values (292, 'Salt - Celery', 39.79);
insert into product (id, name, price) values (293, 'Onions - Red Pearl', 33.28);
insert into product (id, name, price) values (294, 'Plate Foam Laminated 9in Blk', 96.73);
insert into product (id, name, price) values (295, 'Butter - Salted, Micro', 66.68);
insert into product (id, name, price) values (296, 'Long Island Ice Tea', 55.24);
insert into product (id, name, price) values (297, 'French Kiss Vanilla', 57.89);
insert into product (id, name, price) values (298, 'Cheese - Boursin, Garlic / Herbs', 80.47);
insert into product (id, name, price) values (299, 'Bread - Corn Muffaletta', 88.88);
insert into product (id, name, price) values (300, 'Munchies Honey Sweet Trail Mix', 74.45);
insert into product (id, name, price) values (301, 'Squid Ink', 1.66);
insert into product (id, name, price) values (302, 'Snapple - Mango Maddness', 59.54);
insert into product (id, name, price) values (303, 'Pasta - Fusili, Dry', 86.79);
insert into product (id, name, price) values (304, 'Arctic Char - Fillets', 10.05);
insert into product (id, name, price) values (305, 'Water - Spring 1.5lit', 31.63);
insert into product (id, name, price) values (306, 'French Kiss Vanilla', 94.51);
insert into product (id, name, price) values (307, 'Eggplant Oriental', 13.74);
insert into product (id, name, price) values (308, 'Tuna - Bluefin', 47.48);
insert into product (id, name, price) values (309, 'Tart Shells - Sweet, 2', 82.27);
insert into product (id, name, price) values (310, 'Beef - Baby, Liver', 15.33);
insert into product (id, name, price) values (311, 'Garbage Bags - Clear', 49.6);
insert into product (id, name, price) values (312, 'Carbonated Water - Peach', 76.2);
insert into product (id, name, price) values (313, 'Pepper - Chillies, Crushed', 82.7);
insert into product (id, name, price) values (314, 'Bread - Italian Sesame Poly', 23.21);
insert into product (id, name, price) values (315, 'Allspice - Jamaican', 35.7);
insert into product (id, name, price) values (316, 'Bread - Rosemary Focaccia', 78.29);
insert into product (id, name, price) values (317, 'Wanton Wrap', 33.62);
insert into product (id, name, price) values (318, 'Flour - Chickpea', 50.89);
insert into product (id, name, price) values (319, 'Oil - Coconut', 87.94);
insert into product (id, name, price) values (320, 'Sauce - Ranch Dressing', 21.88);
insert into product (id, name, price) values (321, 'Flour - Masa De Harina Mexican', 1.35);
insert into product (id, name, price) values (322, 'Red Cod Fillets - 225g', 2.89);
insert into product (id, name, price) values (323, 'Vacuum Bags 12x16', 28.58);
insert into product (id, name, price) values (324, 'Capicola - Hot', 30.63);
insert into product (id, name, price) values (325, 'Remy Red', 39.54);
insert into product (id, name, price) values (326, 'Wine - Riesling Alsace Ac 2001', 60.57);
insert into product (id, name, price) values (327, 'Salmon Steak - Cohoe 6 Oz', 74.42);
insert into product (id, name, price) values (328, 'Cornish Hen', 64.19);
insert into product (id, name, price) values (329, 'Raisin - Golden', 77.22);
insert into product (id, name, price) values (330, 'Schnappes Peppermint - Walker', 3.02);
insert into product (id, name, price) values (331, 'Pastry - Mini French Pastries', 44.13);
insert into product (id, name, price) values (332, 'Cape Capensis - Fillet', 79.53);
insert into product (id, name, price) values (333, 'Wine - Chenin Blanc K.w.v.', 25.23);
insert into product (id, name, price) values (334, 'Ice Cream - Life Savers', 92.8);
insert into product (id, name, price) values (335, 'Juice - Propel Sport', 18.41);
insert into product (id, name, price) values (336, 'English Muffin', 86.82);
insert into product (id, name, price) values (337, 'Lemon Grass', 75.19);
insert into product (id, name, price) values (338, 'Coffee - Hazelnut Cream', 51.1);
insert into product (id, name, price) values (339, 'Pastry - Trippleberry Muffin - Mini', 59.13);
insert into product (id, name, price) values (340, 'Rambutan', 54.4);
insert into product (id, name, price) values (341, 'Wine - Zonnebloem Pinotage', 76.89);
insert into product (id, name, price) values (342, 'Soup - Campbells Chili', 20.06);
insert into product (id, name, price) values (343, 'Gooseberry', 70.13);
insert into product (id, name, price) values (344, 'Rum - White, Gg White', 77.61);
insert into product (id, name, price) values (345, 'Veal - Nuckle', 56.17);
insert into product (id, name, price) values (346, 'Glass - Juice Clear 5oz 55005', 25.56);
insert into product (id, name, price) values (347, 'Sole - Fillet', 73.07);
insert into product (id, name, price) values (348, 'Chips - Potato Jalapeno', 2.33);
insert into product (id, name, price) values (349, 'Pasta - Gnocchi, Potato', 4.81);
insert into product (id, name, price) values (350, 'Dill - Primerba, Paste', 71.45);
insert into product (id, name, price) values (351, 'Wine - Harrow Estates, Vidal', 81.82);
insert into product (id, name, price) values (352, 'Cumin - Ground', 40.48);
insert into product (id, name, price) values (353, 'Ecolab - Solid Fusion', 62.16);
insert into product (id, name, price) values (354, 'Tortillas - Flour, 8', 50.54);
insert into product (id, name, price) values (355, 'Beef - Rouladin, Sliced', 76.56);
insert into product (id, name, price) values (356, 'Venison - Striploin', 24.35);
insert into product (id, name, price) values (357, 'Cranberries - Dry', 55.61);
insert into product (id, name, price) values (358, 'Kiwi', 47.29);
insert into product (id, name, price) values (359, 'Doilies - 7, Paper', 43.57);
insert into product (id, name, price) values (360, 'Ecolab - Solid Fusion', 71.6);
insert into product (id, name, price) values (361, 'Ezy Change Mophandle', 46.87);
insert into product (id, name, price) values (362, 'Yoplait - Strawbrasp Peac', 40.78);
insert into product (id, name, price) values (363, 'Nantucket - Kiwi Berry Cktl.', 72.89);
insert into product (id, name, price) values (364, 'Cheese - Fontina', 82.92);
insert into product (id, name, price) values (365, 'Laundry - Bag Cloth', 1.45);
insert into product (id, name, price) values (366, 'Bread - Kimel Stick Poly', 63.41);
insert into product (id, name, price) values (367, 'Waffle Stix', 56.54);
insert into product (id, name, price) values (368, 'Urban Zen Drinks', 37.38);
insert into product (id, name, price) values (369, 'Buffalo - Striploin', 68.63);
insert into product (id, name, price) values (370, 'Spice - Greek 1 Step', 81.25);
insert into product (id, name, price) values (371, 'Cleaner - Bleach', 29.52);
insert into product (id, name, price) values (372, 'Wine - Pinot Noir Mondavi Coastal', 39.07);
insert into product (id, name, price) values (373, 'Fish - Scallops, Cold Smoked', 57.18);
insert into product (id, name, price) values (374, 'Flower - Leather Leaf Fern', 19.62);
insert into product (id, name, price) values (375, 'Beer - Corona', 67.9);
insert into product (id, name, price) values (376, 'Sauce - Soy Low Sodium - 3.87l', 61.92);
insert into product (id, name, price) values (377, 'Gherkin - Sour', 25.62);
insert into product (id, name, price) values (378, 'Muffin - Zero Transfat', 3.63);
insert into product (id, name, price) values (379, 'Cakes Assorted', 28.79);
insert into product (id, name, price) values (380, 'Lobster - Tail 6 Oz', 44.12);
insert into product (id, name, price) values (381, 'Beer - Camerons Auburn', 1.68);
insert into product (id, name, price) values (382, 'Garlic - Peeled', 58.86);
insert into product (id, name, price) values (383, 'Jameson - Irish Whiskey', 97.57);
insert into product (id, name, price) values (384, 'Mix - Cocktail Ice Cream', 20.41);
insert into product (id, name, price) values (385, 'Wine - Red, Metus Rose', 85.48);
insert into product (id, name, price) values (386, 'Wine - Rosso Del Veronese Igt', 93.45);
insert into product (id, name, price) values (387, 'Oxtail - Cut', 99.12);
insert into product (id, name, price) values (388, 'Table Cloth 62x120 Colour', 13.76);
insert into product (id, name, price) values (389, 'Parsnip', 94.15);
insert into product (id, name, price) values (390, 'Wine - Prem Select Charddonany', 80.43);
insert into product (id, name, price) values (391, 'Wine - Alicanca Vinho Verde', 7.57);
insert into product (id, name, price) values (392, 'Sloe Gin - Mcguinness', 75.94);
insert into product (id, name, price) values (393, 'Star Anise, Whole', 88.75);
insert into product (id, name, price) values (394, 'Lamb - Loin, Trimmed, Boneless', 33.68);
insert into product (id, name, price) values (395, 'Red Cod Fillets - 225g', 77.08);
insert into product (id, name, price) values (396, 'Coffee - Dark Roast', 97.01);
insert into product (id, name, price) values (397, 'Silicone Paper 16.5x24', 22.74);
insert into product (id, name, price) values (398, 'Pasta - Penne Primavera, Single', 89.57);
insert into product (id, name, price) values (399, 'Chilli Paste, Hot Sambal Oelek', 35.0);
insert into product (id, name, price) values (400, 'Foam Cup 6 Oz', 44.52);
insert into product (id, name, price) values (401, 'Bread - Kimel Stick Poly', 34.58);
insert into product (id, name, price) values (402, 'Table Cloth 81x81 White', 60.63);
insert into product (id, name, price) values (403, 'Rice Pilaf, Dry,package', 52.48);
insert into product (id, name, price) values (404, 'Cauliflower', 51.9);
insert into product (id, name, price) values (405, 'Daikon Radish', 18.59);
insert into product (id, name, price) values (406, 'Tea - Green', 62.55);
insert into product (id, name, price) values (407, 'Chicken - Bones', 39.49);
insert into product (id, name, price) values (408, 'Gatorade - Fruit Punch', 52.28);
insert into product (id, name, price) values (409, 'Snails - Large Canned', 75.01);
insert into product (id, name, price) values (410, 'Fish - Atlantic Salmon, Cold', 48.9);
insert into product (id, name, price) values (411, 'Green Scrubbie Pad H.duty', 30.12);
insert into product (id, name, price) values (412, 'Pop Shoppe Cream Soda', 11.99);
insert into product (id, name, price) values (413, 'Clementine', 81.14);
insert into product (id, name, price) values (414, 'Wine - Chenin Blanc K.w.v.', 3.57);
insert into product (id, name, price) values (415, 'Sobe - Cranberry Grapefruit', 78.64);
insert into product (id, name, price) values (416, 'Chinese Foods - Cantonese', 74.8);
insert into product (id, name, price) values (417, 'Beef - Eye Of Round', 13.52);
insert into product (id, name, price) values (418, 'Bowl 12 Oz - Showcase 92012', 29.95);
insert into product (id, name, price) values (419, 'Pasta - Lasagna Noodle, Frozen', 49.58);
insert into product (id, name, price) values (420, 'Chips - Doritos', 13.85);
insert into product (id, name, price) values (421, 'Peppercorns - Green', 7.44);
insert into product (id, name, price) values (422, 'Wine - Touraine Azay - Le - Rideau', 48.16);
insert into product (id, name, price) values (423, 'Veal - Insides, Grains', 7.07);
insert into product (id, name, price) values (424, 'Fish - Halibut, Cold Smoked', 23.85);
insert into product (id, name, price) values (425, 'Olives - Stuffed', 95.54);
insert into product (id, name, price) values (426, 'Nantucket Cranberry Juice', 35.77);
insert into product (id, name, price) values (427, 'Arctic Char - Fresh, Whole', 14.05);
insert into product (id, name, price) values (428, 'Beer - Fruli', 85.57);
insert into product (id, name, price) values (429, 'Pie Shell - 9', 31.7);
insert into product (id, name, price) values (430, 'Shrimp - Tiger 21/25', 99.96);
insert into product (id, name, price) values (431, 'Samosa - Veg', 57.61);
insert into product (id, name, price) values (432, 'Wine - Port Late Bottled Vintage', 62.33);
insert into product (id, name, price) values (433, 'Nutmeg - Ground', 41.79);
insert into product (id, name, price) values (434, 'Oil - Shortening,liqud, Fry', 8.62);
insert into product (id, name, price) values (435, 'Ostrich - Fan Fillet', 71.2);
insert into product (id, name, price) values (436, 'Bread - Mini Hamburger Bun', 20.08);
insert into product (id, name, price) values (437, 'Oil - Macadamia', 78.85);
insert into product (id, name, price) values (438, 'Plaintain', 36.62);
insert into product (id, name, price) values (439, 'Remy Red Berry Infusion', 34.16);
insert into product (id, name, price) values (440, 'Bread - Rolls, Rye', 48.43);
insert into product (id, name, price) values (441, 'Tart Shells - Savory, 4', 69.5);
insert into product (id, name, price) values (442, 'Croissants Thaw And Serve', 34.55);
insert into product (id, name, price) values (443, 'Oil - Peanut', 85.32);
insert into product (id, name, price) values (444, 'Garbage Bags - Clear', 73.83);
insert into product (id, name, price) values (445, 'Beer - Mcauslan Apricot', 18.52);
insert into product (id, name, price) values (446, 'Easy Off Oven Cleaner', 7.86);
insert into product (id, name, price) values (447, 'Pastry - Cherry Danish - Mini', 41.2);
insert into product (id, name, price) values (448, 'Pears - Fiorelle', 45.44);
insert into product (id, name, price) values (449, 'Sauce Bbq Smokey', 76.71);
insert into product (id, name, price) values (450, 'Lamb - Rack', 13.82);
insert into product (id, name, price) values (451, 'Tea - Jasmin Green', 44.21);
insert into product (id, name, price) values (452, 'Black Currants', 75.46);
insert into product (id, name, price) values (453, 'Chick Peas - Canned', 29.41);
insert into product (id, name, price) values (454, 'Fenngreek Seed', 90.57);
insert into product (id, name, price) values (455, 'Foam Dinner Plate', 33.34);
insert into product (id, name, price) values (456, 'Flower - Commercial Bronze', 57.19);
insert into product (id, name, price) values (457, 'Cookie Dough - Double', 75.38);
insert into product (id, name, price) values (458, 'Yogurt - Banana, 175 Gr', 48.0);
insert into product (id, name, price) values (459, 'Pasta - Lasagne, Fresh', 35.23);
insert into product (id, name, price) values (460, 'Ham Black Forest', 94.4);
insert into product (id, name, price) values (461, 'Wine - Kwv Chenin Blanc South', 84.04);
insert into product (id, name, price) values (462, 'Bread - Crusty Italian Poly', 86.78);
insert into product (id, name, price) values (463, 'Bread - Bagels, Plain', 57.42);
insert into product (id, name, price) values (464, 'Cups 10oz Trans', 91.51);
insert into product (id, name, price) values (465, 'Fuji Apples', 5.64);
insert into product (id, name, price) values (466, 'The Pop Shoppe Pinapple', 98.54);
insert into product (id, name, price) values (467, 'Compound - Strawberry', 35.96);
insert into product (id, name, price) values (468, 'Turkey - Breast, Bone - In', 55.9);
insert into product (id, name, price) values (469, 'Creamers - 10%', 78.83);
insert into product (id, name, price) values (470, 'Ice Cream - Super Sandwich', 23.05);
insert into product (id, name, price) values (471, 'Tomatoes - Roma', 44.91);
insert into product (id, name, price) values (472, 'Pastry - Apple Large', 94.25);
insert into product (id, name, price) values (473, 'Dehydrated Kelp Kombo', 83.29);
insert into product (id, name, price) values (474, 'Straw - Regular', 56.4);
insert into product (id, name, price) values (475, 'Wine - Savigny - Les - Beaune', 66.52);
insert into product (id, name, price) values (476, 'Turnip - Wax', 66.61);
insert into product (id, name, price) values (477, 'Turkey - Breast, Boneless Sk On', 54.89);
insert into product (id, name, price) values (478, 'Cheese - Pont Couvert', 6.57);
insert into product (id, name, price) values (479, 'Walkers Special Old Whiskey', 65.27);
insert into product (id, name, price) values (480, 'Crab Brie In Phyllo', 25.2);
insert into product (id, name, price) values (481, 'Flour Dark Rye', 3.39);
insert into product (id, name, price) values (482, 'Milk - Chocolate 250 Ml', 70.17);
insert into product (id, name, price) values (483, 'Soup - Campbells Pasta Fagioli', 20.93);
insert into product (id, name, price) values (484, 'Split Peas - Green, Dry', 99.35);
insert into product (id, name, price) values (485, 'Vanilla Beans', 50.93);
insert into product (id, name, price) values (486, 'Lettuce - Iceberg', 57.76);
insert into product (id, name, price) values (487, 'Carbonated Water - Orange', 37.77);
insert into product (id, name, price) values (488, 'Wine - Cabernet Sauvignon', 43.12);
insert into product (id, name, price) values (489, 'Carbonated Water - White Grape', 89.81);
insert into product (id, name, price) values (490, 'Passion Fruit', 30.38);
insert into product (id, name, price) values (491, 'Filo Dough', 1.65);
insert into product (id, name, price) values (492, 'Placemat - Scallop, White', 34.56);
insert into product (id, name, price) values (493, 'Veal - Nuckle', 79.91);
insert into product (id, name, price) values (494, 'Duck - Fat', 97.97);
insert into product (id, name, price) values (495, 'Ham - Cooked', 31.1);
insert into product (id, name, price) values (496, 'Vol Au Vents', 33.92);
insert into product (id, name, price) values (497, 'Cup - 3.5oz, Foam', 38.53);
insert into product (id, name, price) values (498, 'Radish', 42.51);
insert into product (id, name, price) values (499, 'Oregano - Fresh', 42.84);
insert into product (id, name, price) values (500, 'Cookie Dough - Oatmeal Rasin', 26.08);
insert into product (id, name, price) values (501, 'Mayonnaise', 41.81);
insert into product (id, name, price) values (502, 'Sherbet - Raspberry', 19.26);
insert into product (id, name, price) values (503, 'Ecolab - Mikroklene 4/4 L', 90.3);
insert into product (id, name, price) values (504, 'Lid Coffeecup 12oz D9542b', 73.51);
insert into product (id, name, price) values (505, 'Stock - Veal, Brown', 25.81);
insert into product (id, name, price) values (506, 'Tea - Camomele', 56.19);
insert into product (id, name, price) values (507, 'Tomatoes - Vine Ripe, Red', 48.65);
insert into product (id, name, price) values (508, 'Cup - 6oz, Foam', 62.35);
insert into product (id, name, price) values (509, 'Vaccum Bag 10x13', 6.63);
insert into product (id, name, price) values (510, 'Wine - Montecillo Rioja Crianza', 33.97);
insert into product (id, name, price) values (511, 'Cheese - Grana Padano', 83.47);
insert into product (id, name, price) values (512, 'Tray - 16in Rnd Blk', 91.49);
insert into product (id, name, price) values (513, 'Napkin - Dinner, White', 3.06);
insert into product (id, name, price) values (514, 'Ice Cream Bar - Hagen Daz', 36.44);
insert into product (id, name, price) values (515, 'Radish - Pickled', 41.51);
insert into product (id, name, price) values (516, 'Squash - Pattypan, Yellow', 15.15);
insert into product (id, name, price) values (517, 'Star Anise, Whole', 33.38);
insert into product (id, name, price) values (518, 'Soup - Campbells, Classic Chix', 48.33);
insert into product (id, name, price) values (519, 'Wine - Gato Negro Cabernet', 16.79);
insert into product (id, name, price) values (520, 'Pasta - Fettuccine, Dry', 4.56);
insert into product (id, name, price) values (521, 'Tea - Orange Pekoe', 31.91);
insert into product (id, name, price) values (522, 'Dooleys Toffee', 37.42);
insert into product (id, name, price) values (523, 'Veal - Sweetbread', 69.12);
insert into product (id, name, price) values (524, 'Initation Crab Meat', 40.75);
insert into product (id, name, price) values (525, 'Veal - Striploin', 82.02);
insert into product (id, name, price) values (526, 'Wine - Tribal Sauvignon', 13.74);
insert into product (id, name, price) values (527, 'Pepper - White, Whole', 88.75);
insert into product (id, name, price) values (528, 'Truffle Cups - Brown', 62.83);
insert into product (id, name, price) values (529, 'Roe - White Fish', 68.02);
insert into product (id, name, price) values (530, 'Apples - Sliced / Wedge', 33.04);
insert into product (id, name, price) values (531, 'Tea - Herbal I Love Lemon', 2.18);
insert into product (id, name, price) values (532, 'Ginger - Fresh', 52.88);
insert into product (id, name, price) values (533, 'Wine - Sicilia Igt Nero Avola', 35.25);
insert into product (id, name, price) values (534, 'Kirsch - Schloss', 61.3);
insert into product (id, name, price) values (535, 'Pants Custom Dry Clean', 20.44);
insert into product (id, name, price) values (536, 'Icecream Cone - Areo Chocolate', 31.4);
insert into product (id, name, price) values (537, 'Wine - Rosso Del Veronese Igt', 76.36);
insert into product (id, name, price) values (538, 'Bread - White, Sliced', 2.66);
insert into product (id, name, price) values (539, 'Soup - French Can Pea', 47.98);
insert into product (id, name, price) values (540, 'Wasabi Paste', 9.79);
insert into product (id, name, price) values (541, 'Plasticspoonblack', 18.25);
insert into product (id, name, price) values (542, 'Chocolate - Liqueur Cups With Foil', 20.89);
insert into product (id, name, price) values (543, 'Green Tea Refresher', 91.08);
insert into product (id, name, price) values (544, 'Coffee Guatemala Dark', 44.97);
insert into product (id, name, price) values (545, 'Pail - 4l White, With Handle', 27.71);
insert into product (id, name, price) values (546, 'Cheese - Brie', 64.44);
insert into product (id, name, price) values (547, 'Cookie Dough - Peanut Butter', 29.43);
insert into product (id, name, price) values (548, 'Bread - Italian Corn Meal Poly', 34.22);
insert into product (id, name, price) values (549, 'Coconut - Shredded, Sweet', 31.92);
insert into product (id, name, price) values (550, 'Steampan - Foil', 40.87);
insert into product (id, name, price) values (551, 'Sauce - Hoisin', 71.64);
insert into product (id, name, price) values (552, 'Momiji Oroshi Chili Sauce', 34.47);
insert into product (id, name, price) values (553, 'Taro Leaves', 68.16);
insert into product (id, name, price) values (554, 'Soup V8 Roasted Red Pepper', 26.56);
insert into product (id, name, price) values (555, 'Soap - Hand Soap', 79.43);
insert into product (id, name, price) values (556, 'Clams - Littleneck, Whole', 22.05);
insert into product (id, name, price) values (557, 'Melon - Watermelon Yellow', 1.14);
insert into product (id, name, price) values (558, 'Squash - Butternut', 46.44);
insert into product (id, name, price) values (559, 'Soup - Knorr, Chicken Gumbo', 28.48);
insert into product (id, name, price) values (560, 'Mcguinness - Blue Curacao', 59.09);
insert into product (id, name, price) values (561, 'Mushroom - Morel Frozen', 33.84);
insert into product (id, name, price) values (562, 'Chicken - White Meat With Tender', 26.77);
insert into product (id, name, price) values (563, 'Muffin Hinge - 211n', 51.69);
insert into product (id, name, price) values (564, 'Mix - Cappucino Cocktail', 8.8);
insert into product (id, name, price) values (565, 'Bag - Clear 7 Lb', 34.05);
insert into product (id, name, price) values (566, 'Salmon Steak - Cohoe 8 Oz', 79.24);
insert into product (id, name, price) values (567, 'Spinach - Baby', 51.62);
insert into product (id, name, price) values (568, 'Chocolate - Dark', 80.51);
insert into product (id, name, price) values (569, 'Carbonated Water - Blackberry', 33.45);
insert into product (id, name, price) values (570, 'Beans - Soya Bean', 95.51);
insert into product (id, name, price) values (571, 'Juice - Lemon', 81.63);
insert into product (id, name, price) values (572, 'Pork - Suckling Pig', 63.38);
insert into product (id, name, price) values (573, 'Mustard - Pommery', 74.73);
insert into product (id, name, price) values (574, 'Appetizer - Mushroom Tart', 76.5);
insert into product (id, name, price) values (575, 'Bread - Italian Corn Meal Poly', 1.2);
insert into product (id, name, price) values (576, 'Grapes - Red', 13.6);
insert into product (id, name, price) values (577, 'Beef - Tender Tips', 68.97);
insert into product (id, name, price) values (578, 'Yams', 2.39);
insert into product (id, name, price) values (579, 'Peas - Frozen', 99.97);
insert into product (id, name, price) values (580, 'Yokaline', 8.36);
insert into product (id, name, price) values (581, 'Island Oasis - Wildberry', 16.32);
insert into product (id, name, price) values (582, 'Pasta - Linguini, Dry', 74.76);
insert into product (id, name, price) values (583, 'Oil - Pumpkinseed', 82.36);
insert into product (id, name, price) values (584, 'Kale - Red', 67.88);
insert into product (id, name, price) values (585, 'Olives - Stuffed', 2.2);
insert into product (id, name, price) values (586, 'Salmon - Smoked, Sliced', 11.8);
insert into product (id, name, price) values (587, 'Garam Marsala', 44.01);
insert into product (id, name, price) values (588, 'Crab - Back Fin Meat, Canned', 23.59);
insert into product (id, name, price) values (589, 'Sausage - Chorizo', 35.01);
insert into product (id, name, price) values (590, 'Cookie Dough - Chunky', 74.35);
insert into product (id, name, price) values (591, 'Chips Potato Swt Chilli Sour', 88.22);
insert into product (id, name, price) values (592, 'Pasta - Penne, Lisce, Dry', 13.12);
insert into product (id, name, price) values (593, 'Mcguinness - Blue Curacao', 39.01);
insert into product (id, name, price) values (594, 'Turkey Tenderloin Frozen', 11.95);
insert into product (id, name, price) values (595, 'Beer - Camerons Cream Ale', 26.17);
insert into product (id, name, price) values (596, 'Trueblue - Blueberry Cranberry', 34.88);
insert into product (id, name, price) values (597, 'Wine - Soave Folonari', 22.62);
insert into product (id, name, price) values (598, 'Beef - Bresaola', 44.49);
insert into product (id, name, price) values (599, 'Cheese - Provolone', 36.25);
insert into product (id, name, price) values (600, 'Sugar - Monocystal / Rock', 1.07);
insert into product (id, name, price) values (601, 'Sole - Iqf', 46.79);
insert into product (id, name, price) values (602, 'Shrimp - Black Tiger 8 - 12', 69.11);
insert into product (id, name, price) values (603, 'Pasta - Cannelloni, Sheets, Fresh', 74.39);
insert into product (id, name, price) values (604, 'Pepper - Black, Ground', 34.46);
insert into product (id, name, price) values (605, 'Huck Towels White', 62.66);
insert into product (id, name, price) values (606, 'Mustard - Dijon', 84.4);
insert into product (id, name, price) values (607, 'Cheese - Shred Cheddar / Mozza', 90.63);
insert into product (id, name, price) values (608, 'Smoked Tongue', 67.11);
insert into product (id, name, price) values (609, 'Guinea Fowl', 8.19);
insert into product (id, name, price) values (610, 'Bulgar', 57.6);
insert into product (id, name, price) values (611, 'Bread - Rosemary Focaccia', 6.16);
insert into product (id, name, price) values (612, 'Plastic Wrap', 62.93);
insert into product (id, name, price) values (613, 'Vodka - Lemon, Absolut', 11.54);
insert into product (id, name, price) values (614, 'Oil - Cooking Spray', 62.15);
insert into product (id, name, price) values (615, 'Foil Wrap', 32.34);
insert into product (id, name, price) values (616, 'Island Oasis - Raspberry', 78.11);
insert into product (id, name, price) values (617, 'Wine - Sauvignon Blanc Oyster', 41.87);
insert into product (id, name, price) values (618, 'Black Currants', 3.86);
insert into product (id, name, price) values (619, 'Beef Cheek Fresh', 31.45);
insert into product (id, name, price) values (620, 'Tart - Butter Plain Squares', 42.5);
insert into product (id, name, price) values (621, 'Cake - French Pear Tart', 65.55);
insert into product (id, name, price) values (622, 'Trout - Rainbow, Frozen', 29.72);
insert into product (id, name, price) values (623, 'Beer - Sleeman Fine Porter', 70.1);
insert into product (id, name, price) values (624, 'Broom - Corn', 23.22);
insert into product (id, name, price) values (625, 'Table Cloth 72x144 White', 30.05);
insert into product (id, name, price) values (626, 'Island Oasis - Mango Daiquiri', 37.55);
insert into product (id, name, price) values (627, 'Juice - Propel Sport', 80.75);
insert into product (id, name, price) values (628, 'Blueberries - Frozen', 53.41);
insert into product (id, name, price) values (629, 'Coffee - Dark Roast', 80.66);
insert into product (id, name, price) values (630, 'Mix - Cappucino Cocktail', 32.51);
insert into product (id, name, price) values (631, 'Doilies - 5, Paper', 81.47);
insert into product (id, name, price) values (632, 'Petit Baguette', 25.42);
insert into product (id, name, price) values (633, 'Cheese - Brie, Triple Creme', 28.62);
insert into product (id, name, price) values (634, 'Tea - Grapefruit Green Tea', 92.26);
insert into product (id, name, price) values (635, 'Yeast Dry - Fermipan', 26.07);
insert into product (id, name, price) values (636, 'Wine - Sawmill Creek Autumn', 40.48);
insert into product (id, name, price) values (637, 'Bok Choy - Baby', 82.81);
insert into product (id, name, price) values (638, 'Pasta - Penne, Rigate, Dry', 52.7);
insert into product (id, name, price) values (639, 'Apricots - Dried', 41.74);
insert into product (id, name, price) values (640, 'Basil - Fresh', 59.26);
insert into product (id, name, price) values (641, 'Soup - Knorr, Chicken Noodle', 31.11);
insert into product (id, name, price) values (642, 'Ice Cream - Super Sandwich', 21.15);
insert into product (id, name, price) values (643, 'Olives - Black, Pitted', 28.64);
insert into product (id, name, price) values (644, 'Hickory Smoke, Liquid', 24.85);
insert into product (id, name, price) values (645, 'Beef - Ground, Extra Lean, Fresh', 18.6);
insert into product (id, name, price) values (646, 'Melon - Watermelon Yellow', 92.57);
insert into product (id, name, price) values (647, 'Coffee - Dark Roast', 62.0);
insert into product (id, name, price) values (648, 'Beans - Kidney, Canned', 71.89);
insert into product (id, name, price) values (649, 'Soup - Campbells Mac N Cheese', 96.35);
insert into product (id, name, price) values (650, 'Plate - Foam, Bread And Butter', 83.09);
insert into product (id, name, price) values (651, 'Nut - Macadamia', 64.05);
insert into product (id, name, price) values (652, 'Curry Paste - Green Masala', 90.97);
insert into product (id, name, price) values (653, 'Nestea - Ice Tea, Diet', 33.61);
insert into product (id, name, price) values (654, 'Wine - White, Concha Y Toro', 24.73);
insert into product (id, name, price) values (655, 'Cookies Oatmeal Raisin', 75.23);
insert into product (id, name, price) values (656, 'Chick Peas - Dried', 99.95);
insert into product (id, name, price) values (657, 'Dr. Pepper - 355ml', 55.32);
insert into product (id, name, price) values (658, 'Beef - Sushi Flat Iron Steak', 44.66);
insert into product (id, name, price) values (659, 'Celery Root', 8.37);
insert into product (id, name, price) values (660, 'Cup - 4oz Translucent', 76.42);
insert into product (id, name, price) values (661, 'Dill Weed - Fresh', 47.64);
insert into product (id, name, price) values (662, 'Oil - Shortening,liqud, Fry', 49.42);
insert into product (id, name, price) values (663, 'Greens Mustard', 2.57);
insert into product (id, name, price) values (664, 'Wine - Harrow Estates, Vidal', 89.7);
insert into product (id, name, price) values (665, 'Foam Tray S2', 34.76);
insert into product (id, name, price) values (666, 'Jam - Marmalade, Orange', 87.29);
insert into product (id, name, price) values (667, 'Sauce - Salsa', 57.71);
insert into product (id, name, price) values (668, 'Squid Ink', 40.04);
insert into product (id, name, price) values (669, 'Wine - Periguita Fonseca', 78.95);
insert into product (id, name, price) values (670, 'Cake - Dulce De Leche', 48.06);
insert into product (id, name, price) values (671, 'Flour - Semolina', 57.83);
insert into product (id, name, price) values (672, 'Pasta - Lasagna Noodle, Frozen', 52.42);
insert into product (id, name, price) values (673, 'Wine - Zonnebloem Pinotage', 3.01);
insert into product (id, name, price) values (674, 'Petit Baguette', 12.12);
insert into product (id, name, price) values (675, 'Chocolate Bar - Coffee Crisp', 99.0);
insert into product (id, name, price) values (676, 'Mcguinness - Blue Curacao', 9.11);
insert into product (id, name, price) values (677, 'Otomegusa Dashi Konbu', 15.78);
insert into product (id, name, price) values (678, 'Bonito Flakes - Toku Katsuo', 44.28);
insert into product (id, name, price) values (679, 'Sherry - Dry', 9.16);
insert into product (id, name, price) values (680, 'Wine - Niagara Peninsula Vqa', 74.97);
insert into product (id, name, price) values (681, 'Bar Energy Chocchip', 65.92);
insert into product (id, name, price) values (682, 'Water - Tonic', 29.95);
insert into product (id, name, price) values (683, 'Soap - Mr.clean Floor Soap', 14.36);
insert into product (id, name, price) values (684, 'Water - Tonic', 72.81);
insert into product (id, name, price) values (685, 'Cheese - Havarti, Salsa', 69.21);
insert into product (id, name, price) values (686, 'Roe - White Fish', 69.29);
insert into product (id, name, price) values (687, 'Lobster - Baby, Boiled', 19.18);
insert into product (id, name, price) values (688, 'Wine - Red, Pelee Island Merlot', 59.29);
insert into product (id, name, price) values (689, 'Roe - Flying Fish', 39.6);
insert into product (id, name, price) values (690, 'Chef Hat 25cm', 89.3);
insert into product (id, name, price) values (691, 'Swiss Chard - Red', 71.63);
insert into product (id, name, price) values (692, 'Milk - 2%', 71.69);
insert into product (id, name, price) values (693, 'Cheese - Ricotta', 87.68);
insert into product (id, name, price) values (694, 'Beer - Tetleys', 36.89);
insert into product (id, name, price) values (695, 'Chicken - Wings, Tip Off', 89.46);
insert into product (id, name, price) values (696, 'Beef - Bones, Cut - Up', 15.96);
insert into product (id, name, price) values (697, 'Table Cloth 81x81 Colour', 10.08);
insert into product (id, name, price) values (698, 'Duck - Legs', 25.99);
insert into product (id, name, price) values (699, 'Soup Knorr Chili With Beans', 16.7);
insert into product (id, name, price) values (700, 'Wine - Rosso Toscano Igt', 40.64);
insert into product (id, name, price) values (701, 'Pasta - Rotini, Colour, Dry', 56.59);
insert into product (id, name, price) values (702, 'Table Cloth 72x144 White', 22.92);
insert into product (id, name, price) values (703, 'Bread - Multigrain, Loaf', 8.83);
insert into product (id, name, price) values (704, 'Nut - Pistachio, Shelled', 40.71);
insert into product (id, name, price) values (705, 'Lemonade - Island Tea, 591 Ml', 46.36);
insert into product (id, name, price) values (706, 'Mushroom - Oyster, Fresh', 90.18);
insert into product (id, name, price) values (707, 'Couscous', 65.17);
insert into product (id, name, price) values (708, 'Chilli Paste, Sambal Oelek', 6.16);
insert into product (id, name, price) values (709, 'Cake - Mini Potato Pancake', 99.2);
insert into product (id, name, price) values (710, 'Drambuie', 50.11);
insert into product (id, name, price) values (711, 'Pepperoni Slices', 57.03);
insert into product (id, name, price) values (712, 'Rice Paper', 41.8);
insert into product (id, name, price) values (713, 'Zucchini - Yellow', 60.08);
insert into product (id, name, price) values (714, 'Instant Coffee', 93.74);
insert into product (id, name, price) values (715, 'Pastry - Cherry Danish - Mini', 54.78);
insert into product (id, name, price) values (716, 'Kellogs All Bran Bars', 71.96);
insert into product (id, name, price) values (717, 'Cheese - Camembert', 33.54);
insert into product (id, name, price) values (718, 'Baking Soda', 86.41);
insert into product (id, name, price) values (719, 'Sauce - Soy Low Sodium - 3.87l', 46.49);
insert into product (id, name, price) values (720, 'Lamb - Loin, Trimmed, Boneless', 94.9);
insert into product (id, name, price) values (721, 'Wine - Domaine Boyar Royal', 7.26);
insert into product (id, name, price) values (722, 'Wine - White Cab Sauv.on', 29.14);
insert into product (id, name, price) values (723, 'Pickerel - Fillets', 77.62);
insert into product (id, name, price) values (724, 'Tomato - Green', 95.49);
insert into product (id, name, price) values (725, 'The Pop Shoppe - Root Beer', 75.65);
insert into product (id, name, price) values (726, 'Urban Zen Drinks', 37.12);
insert into product (id, name, price) values (727, 'Oil - Truffle, Black', 80.45);
insert into product (id, name, price) values (728, 'Calaloo', 67.65);
insert into product (id, name, price) values (729, 'Samosa - Veg', 1.43);
insert into product (id, name, price) values (730, 'Salmon Steak - Cohoe 6 Oz', 80.71);
insert into product (id, name, price) values (731, 'Bread - Roll, Italian', 80.08);
insert into product (id, name, price) values (732, 'Cheese - Brie,danish', 17.26);
insert into product (id, name, price) values (733, 'Shopper Bag - S - 4', 65.01);
insert into product (id, name, price) values (734, 'Wine - Magnotta - Belpaese', 8.06);
insert into product (id, name, price) values (735, 'Sponge Cake Mix - Chocolate', 59.53);
insert into product (id, name, price) values (736, 'Coffee Cup 12oz 5342cd', 63.03);
insert into product (id, name, price) values (737, 'Vinegar - Red Wine', 91.67);
insert into product (id, name, price) values (738, 'Coffee Guatemala Dark', 41.35);
insert into product (id, name, price) values (739, 'Bread Base - Goodhearth', 26.17);
insert into product (id, name, price) values (740, 'Corn - Mini', 13.91);
insert into product (id, name, price) values (741, 'Cheese - Pont Couvert', 34.07);
insert into product (id, name, price) values (742, 'Tart Shells - Sweet, 3', 12.76);
insert into product (id, name, price) values (743, 'Turkey - Whole, Fresh', 56.07);
insert into product (id, name, price) values (744, 'Soup - Campbells Mushroom', 17.6);
insert into product (id, name, price) values (745, 'Soup Knorr Chili With Beans', 54.23);
insert into product (id, name, price) values (746, 'Energy - Boo - Koo', 49.26);
insert into product (id, name, price) values (747, 'Extract - Almond', 1.52);
insert into product (id, name, price) values (748, 'Water - Evian 355 Ml', 30.08);
insert into product (id, name, price) values (749, 'Pastry - Carrot Muffin - Mini', 71.22);
insert into product (id, name, price) values (750, 'Stock - Fish', 61.48);
insert into product (id, name, price) values (751, 'Water - Green Tea Refresher', 58.43);
insert into product (id, name, price) values (752, 'Banana - Green', 43.96);
insert into product (id, name, price) values (753, 'Bagel - Everything', 4.17);
insert into product (id, name, price) values (754, 'Carbonated Water - Raspberry', 42.94);
insert into product (id, name, price) values (755, 'Zucchini - Green', 91.82);
insert into product (id, name, price) values (756, 'Grapes - Green', 49.18);
insert into product (id, name, price) values (757, 'Sugar - Brown, Individual', 26.53);
insert into product (id, name, price) values (758, 'Eel Fresh', 55.31);
insert into product (id, name, price) values (759, 'Chips - Doritos', 7.87);
insert into product (id, name, price) values (760, 'Mustard - Pommery', 74.73);
insert into product (id, name, price) values (761, 'Container - Clear 32 Oz', 74.76);
insert into product (id, name, price) values (762, 'Tea - Apple Green Tea', 80.81);
insert into product (id, name, price) values (763, 'Soup - Campbells, Spinach Crm', 10.74);
insert into product (id, name, price) values (764, 'Soup - French Onion', 53.58);
insert into product (id, name, price) values (765, 'Tuna - Sushi Grade', 21.4);
insert into product (id, name, price) values (766, 'Sour Puss - Tangerine', 92.12);
insert into product (id, name, price) values (767, 'Liquid Aminios Acid - Braggs', 43.56);
insert into product (id, name, price) values (768, 'Pork Loin Cutlets', 19.07);
insert into product (id, name, price) values (769, 'Asparagus - Green, Fresh', 45.09);
insert into product (id, name, price) values (770, 'Fish - Base, Bouillion', 15.99);
insert into product (id, name, price) values (771, 'Radish - Pickled', 42.01);
insert into product (id, name, price) values (772, 'Sprouts - Brussel', 98.56);
insert into product (id, name, price) values (773, 'Lamb - Whole, Fresh', 45.59);
insert into product (id, name, price) values (774, 'Beans - Navy, Dry', 4.65);
insert into product (id, name, price) values (775, 'Tuna - Salad Premix', 54.6);
insert into product (id, name, price) values (776, 'Beer - Sleemans Cream Ale', 27.77);
insert into product (id, name, price) values (777, 'Pants Custom Dry Clean', 43.19);
insert into product (id, name, price) values (778, 'Beets - Mini Golden', 89.63);
insert into product (id, name, price) values (779, 'Chicken - Ground', 14.37);
insert into product (id, name, price) values (780, 'Ecolab - Hand Soap Form Antibac', 68.06);
insert into product (id, name, price) values (781, 'Chicken - Soup Base', 94.78);
insert into product (id, name, price) values (782, 'Appetizer - Southwestern', 3.18);
insert into product (id, name, price) values (783, 'Muffin Batt - Carrot Spice', 59.07);
insert into product (id, name, price) values (784, 'Tea - Herbal Sweet Dreams', 93.1);
insert into product (id, name, price) values (785, 'Wine - Fat Bastard Merlot', 24.87);
insert into product (id, name, price) values (786, 'Cookies - Oreo, 4 Pack', 56.85);
insert into product (id, name, price) values (787, 'Cake - French Pear Tart', 31.2);
insert into product (id, name, price) values (788, 'Fish - Bones', 46.15);
insert into product (id, name, price) values (789, 'Curry Paste - Madras', 30.16);
insert into product (id, name, price) values (790, 'Ice - Clear, 300 Lb For Carving', 40.62);
insert into product (id, name, price) values (791, 'Wine - Saint Emilion Calvet', 81.98);
insert into product (id, name, price) values (792, 'Lamb - Ground', 26.65);
insert into product (id, name, price) values (793, 'Wine - Ruffino Chianti', 63.64);
insert into product (id, name, price) values (794, 'Ginger - Crystalized', 91.43);
insert into product (id, name, price) values (795, 'Beans - French', 75.08);
insert into product (id, name, price) values (796, 'Beer - Moosehead', 19.86);
insert into product (id, name, price) values (797, 'Table Cloth 54x54 White', 26.39);
insert into product (id, name, price) values (798, 'Tabasco Sauce, 2 Oz', 81.16);
insert into product (id, name, price) values (799, 'Muffin - Mix - Creme Brule 15l', 15.52);
insert into product (id, name, price) values (800, 'Sausage - Liver', 27.33);
insert into product (id, name, price) values (801, 'Squash - Pepper', 78.29);
insert into product (id, name, price) values (802, 'Muffin - Mix - Strawberry Rhubarb', 32.02);
insert into product (id, name, price) values (803, 'Wine - Savigny - Les - Beaune', 19.49);
insert into product (id, name, price) values (804, 'Lettuce - Lambs Mash', 5.85);
insert into product (id, name, price) values (805, 'Carbonated Water - Blackcherry', 88.46);
insert into product (id, name, price) values (806, 'Beets - Pickled', 24.72);
insert into product (id, name, price) values (807, 'Wheat - Soft Kernal Of Wheat', 42.23);
insert into product (id, name, price) values (808, 'Rice - Wild', 86.33);
insert into product (id, name, price) values (809, 'Wine - Jaboulet Cotes Du Rhone', 56.8);
insert into product (id, name, price) values (810, 'Versatainer Nc - 8288', 84.31);
insert into product (id, name, price) values (811, 'Pasta - Lasagne, Fresh', 54.98);
insert into product (id, name, price) values (812, 'Buffalo - Short Rib Fresh', 44.3);
insert into product (id, name, price) values (813, 'Oranges', 95.76);
insert into product (id, name, price) values (814, 'Tomatoes - Cherry, Yellow', 1.91);
insert into product (id, name, price) values (815, 'Flavouring Vanilla Artificial', 19.81);
insert into product (id, name, price) values (816, 'Sage - Fresh', 14.42);
insert into product (id, name, price) values (817, 'Wine - Sherry Dry Sack, William', 36.99);
insert into product (id, name, price) values (818, 'Rosemary - Fresh', 13.22);
insert into product (id, name, price) values (819, 'Marzipan 50/50', 52.24);
insert into product (id, name, price) values (820, 'Wine - Sawmill Creek Autumn', 58.39);
insert into product (id, name, price) values (821, 'Chick Peas - Canned', 51.08);
insert into product (id, name, price) values (822, 'Pasta - Fusili, Dry', 46.89);
insert into product (id, name, price) values (823, 'Nutmeg - Ground', 69.49);
insert into product (id, name, price) values (824, 'Garbage Bags - Black', 3.08);
insert into product (id, name, price) values (825, 'Toothpick Frilled', 48.72);
insert into product (id, name, price) values (826, 'Apple - Custard', 46.38);
insert into product (id, name, price) values (827, 'Cookie Dough - Peanut Butter', 67.97);
insert into product (id, name, price) values (828, 'Water - Green Tea Refresher', 45.95);
insert into product (id, name, price) values (829, 'Tarts Assorted', 73.33);
insert into product (id, name, price) values (830, 'Beer - Creemore', 96.87);
insert into product (id, name, price) values (831, 'Myers Planters Punch', 16.27);
insert into product (id, name, price) values (832, 'Coffee Beans - Chocolate', 48.65);
insert into product (id, name, price) values (833, 'Cake Slab', 13.54);
insert into product (id, name, price) values (834, 'Garlic Powder', 39.87);
insert into product (id, name, price) values (835, 'Foam Cup 6 Oz', 49.52);
insert into product (id, name, price) values (836, 'Beans - Black Bean, Preserved', 98.1);
insert into product (id, name, price) values (837, 'Turkey - Whole, Fresh', 72.42);
insert into product (id, name, price) values (838, 'Cake Sheet Combo Party Pack', 29.52);
insert into product (id, name, price) values (839, 'Absolut Citron', 87.6);
insert into product (id, name, price) values (840, 'Sugar - Invert', 48.02);
insert into product (id, name, price) values (841, 'Vol Au Vents', 94.57);
insert into product (id, name, price) values (842, 'Pur Source', 96.09);
insert into product (id, name, price) values (843, 'Soap - Mr.clean Floor Soap', 35.09);
insert into product (id, name, price) values (844, 'Breakfast Quesadillas', 62.4);
insert into product (id, name, price) values (845, 'Water - Aquafina Vitamin', 28.01);
insert into product (id, name, price) values (846, 'Foil Wrap', 34.62);
insert into product (id, name, price) values (847, 'Beef - Ox Tongue', 67.34);
insert into product (id, name, price) values (848, 'Langers - Ruby Red Grapfruit', 91.69);
insert into product (id, name, price) values (849, 'Muffin Hinge Container 6', 19.95);
insert into product (id, name, price) values (850, 'Pie Shell - 5', 89.25);
insert into product (id, name, price) values (851, 'Lamb - Racks, Frenched', 52.23);
insert into product (id, name, price) values (852, 'Chips - Miss Vickies', 91.56);
insert into product (id, name, price) values (853, 'Container Clear 8 Oz', 87.94);
insert into product (id, name, price) values (854, 'Iced Tea Concentrate', 71.26);
insert into product (id, name, price) values (855, 'Nori Sea Weed', 39.5);
insert into product (id, name, price) values (856, 'V8 - Berry Blend', 96.57);
insert into product (id, name, price) values (857, 'Pork Ham Prager', 78.51);
insert into product (id, name, price) values (858, 'Pears - Anjou', 18.42);
insert into product (id, name, price) values (859, 'Arctic Char - Fillets', 24.32);
insert into product (id, name, price) values (860, 'Chinese Foods - Chicken Wing', 37.6);
insert into product (id, name, price) values (861, 'Wine - Chablis 2003 Champs', 27.64);
insert into product (id, name, price) values (862, 'Filter - Coffee', 11.28);
insert into product (id, name, price) values (863, 'Bread - Roll, Whole Wheat', 49.87);
insert into product (id, name, price) values (864, 'Salmon - Smoked, Sliced', 81.99);
insert into product (id, name, price) values (865, 'Apple - Granny Smith', 16.3);
insert into product (id, name, price) values (866, 'Soup - Knorr, Veg / Beef', 2.16);
insert into product (id, name, price) values (867, 'Juice - V8, Tomato', 3.07);
insert into product (id, name, price) values (868, 'Rappini - Andy Boy', 49.9);
insert into product (id, name, price) values (869, 'Cake - Mini Cheesecake', 47.98);
insert into product (id, name, price) values (870, 'Wine - Champagne Brut Veuve', 3.71);
insert into product (id, name, price) values (871, 'Truffle Cups - White Paper', 46.15);
insert into product (id, name, price) values (872, 'Mushroom - Enoki, Fresh', 31.67);
insert into product (id, name, price) values (873, 'Bag - Regular Kraft 20 Lb', 2.48);
insert into product (id, name, price) values (874, 'Potatoes - Parissienne', 54.16);
insert into product (id, name, price) values (875, 'Soup - Campbells Beef Strogonoff', 96.13);
insert into product (id, name, price) values (876, 'Cleaner - Bleach', 84.87);
insert into product (id, name, price) values (877, 'Garam Marsala', 41.35);
insert into product (id, name, price) values (878, 'Wine - Ej Gallo Sonoma', 64.45);
insert into product (id, name, price) values (879, 'Beef - Cooked, Corned', 65.58);
insert into product (id, name, price) values (880, 'Kiwi', 12.05);
insert into product (id, name, price) values (881, 'Beef - Tongue, Fresh', 97.97);
insert into product (id, name, price) values (882, 'Muffins - Assorted', 37.67);
insert into product (id, name, price) values (883, 'Rabbit - Whole', 54.81);
insert into product (id, name, price) values (884, 'Wine - Ruffino Chianti Classico', 94.39);
insert into product (id, name, price) values (885, 'Rootbeer', 81.75);
insert into product (id, name, price) values (886, 'Veal - Inside', 72.84);
insert into product (id, name, price) values (887, 'Cabbage - Red', 6.02);
insert into product (id, name, price) values (888, 'Baking Soda', 98.5);
insert into product (id, name, price) values (889, 'Pepper - Cubanelle', 19.86);
insert into product (id, name, price) values (890, 'Cardamon Seed / Pod', 89.4);
insert into product (id, name, price) values (891, 'Blueberries', 20.28);
insert into product (id, name, price) values (892, 'Tomatoes - Cherry', 40.79);
insert into product (id, name, price) values (893, 'Coffee - Decafenated', 74.79);
insert into product (id, name, price) values (894, 'Spice - Onion Powder Granulated', 65.86);
insert into product (id, name, price) values (895, 'Lemonade - Natural, 591 Ml', 90.53);
insert into product (id, name, price) values (896, 'Pasta - Shells, Medium, Dry', 67.46);
insert into product (id, name, price) values (897, 'Cheese - Parmigiano Reggiano', 6.75);
insert into product (id, name, price) values (898, 'Pasta - Fett Alfredo, Single Serve', 10.81);
insert into product (id, name, price) values (899, 'Chips - Assorted', 44.52);
insert into product (id, name, price) values (900, 'Container - Hngd Cll Blk 7x7x3', 19.1);
insert into product (id, name, price) values (901, 'Fib N9 - Prague Powder', 9.87);
insert into product (id, name, price) values (902, 'Sprouts - China Rose', 27.89);
insert into product (id, name, price) values (903, 'Wine - Wyndham Estate Bin 777', 68.44);
insert into product (id, name, price) values (904, 'Pork Casing', 77.96);
insert into product (id, name, price) values (905, 'Spinach - Frozen', 88.04);
insert into product (id, name, price) values (906, 'Veal - Insides Provini', 75.79);
insert into product (id, name, price) values (907, 'V8 - Tropical Blend', 11.63);
insert into product (id, name, price) values (908, 'Sloe Gin - Mcguinness', 58.03);
insert into product (id, name, price) values (909, 'Chocolate Bar - Oh Henry', 74.6);
insert into product (id, name, price) values (910, 'Icecream - Dstk Super Cone', 31.34);
insert into product (id, name, price) values (911, 'Cheese - Woolwich Goat, Log', 43.37);
insert into product (id, name, price) values (912, 'Kellogs All Bran Bars', 66.31);
insert into product (id, name, price) values (913, 'Sugar - White Packet', 78.96);
insert into product (id, name, price) values (914, 'Momiji Oroshi Chili Sauce', 45.78);
insert into product (id, name, price) values (915, 'Nantucket - Orange Mango Cktl', 33.28);
insert into product (id, name, price) values (916, 'Sugar - Monocystal / Rock', 83.83);
insert into product (id, name, price) values (917, 'V8 Splash Strawberry Banana', 3.47);
insert into product (id, name, price) values (918, 'Sauce - Salsa', 64.7);
insert into product (id, name, price) values (919, 'Steampan Lid', 7.87);
insert into product (id, name, price) values (920, 'Nut - Peanut, Roasted', 66.4);
insert into product (id, name, price) values (921, 'Wine - Valpolicella Masi', 49.41);
insert into product (id, name, price) values (922, 'Wine - Valpolicella Masi', 90.42);
insert into product (id, name, price) values (923, 'Wine - Bouchard La Vignee Pinot', 40.49);
insert into product (id, name, price) values (924, 'Chocolate Liqueur - Godet White', 9.78);
insert into product (id, name, price) values (925, 'Wine - Red, Black Opal Shiraz', 31.11);
insert into product (id, name, price) values (926, 'Garam Masala Powder', 67.95);
insert into product (id, name, price) values (927, 'Thyme - Dried', 94.13);
insert into product (id, name, price) values (928, 'Turkey Tenderloin Frozen', 64.62);
insert into product (id, name, price) values (929, 'Cake - French Pear Tart', 88.18);
insert into product (id, name, price) values (930, 'Icecream - Dstk Strw Chseck', 58.45);
insert into product (id, name, price) values (931, 'Soho Lychee Liqueur', 6.46);
insert into product (id, name, price) values (932, 'Potatoes - Peeled', 69.28);
insert into product (id, name, price) values (933, 'Chinese Foods - Thick Noodles', 22.46);
insert into product (id, name, price) values (934, 'Towel - Roll White', 11.88);
insert into product (id, name, price) values (935, 'Savory', 95.23);
insert into product (id, name, price) values (936, 'Wine - Puligny Montrachet A.', 47.44);
insert into product (id, name, price) values (937, 'Duck - Whole', 39.86);
insert into product (id, name, price) values (938, 'Potatoes - Mini White 3 Oz', 33.41);
insert into product (id, name, price) values (939, 'Tuna - Salad Premix', 33.29);
insert into product (id, name, price) values (940, 'Pork - Loin, Center Cut', 60.69);
insert into product (id, name, price) values (941, 'Chocolate - Milk, Callets', 76.43);
insert into product (id, name, price) values (942, 'Sun - Dried Tomatoes', 17.01);
insert into product (id, name, price) values (943, 'Carbonated Water - Blackberry', 44.05);
insert into product (id, name, price) values (944, 'Muffin Mix - Lemon Cranberry', 9.23);
insert into product (id, name, price) values (945, 'Tomatoes - Hot House', 4.12);
insert into product (id, name, price) values (946, 'Paper Towel Touchless', 18.1);
insert into product (id, name, price) values (947, 'Flour - Bran, Red', 74.73);
insert into product (id, name, price) values (948, 'Pork - Back, Long Cut, Boneless', 43.64);
insert into product (id, name, price) values (949, 'Cheese - Stilton', 5.39);
insert into product (id, name, price) values (950, 'Puree - Pear', 8.53);
insert into product (id, name, price) values (951, 'Cheese - Shred Cheddar / Mozza', 48.55);
insert into product (id, name, price) values (952, 'Blouse / Shirt / Sweater', 87.35);
insert into product (id, name, price) values (953, 'Wine - Lou Black Shiraz', 41.49);
insert into product (id, name, price) values (954, 'Sprite, Diet - 355ml', 6.04);
insert into product (id, name, price) values (955, 'Nantucket - Pomegranate Pear', 62.45);
insert into product (id, name, price) values (956, 'Beer - Moosehead', 63.52);
insert into product (id, name, price) values (957, 'Cheese - Goat With Herbs', 26.19);
insert into product (id, name, price) values (958, 'Soup - Campbells Pasta Fagioli', 2.59);
insert into product (id, name, price) values (959, 'Bag - Clear 7 Lb', 55.8);
insert into product (id, name, price) values (960, 'Chicken - Wings, Tip Off', 78.29);
insert into product (id, name, price) values (961, 'Wine - Saint Emilion Calvet', 33.72);
insert into product (id, name, price) values (962, 'Appetiser - Bought', 13.45);
insert into product (id, name, price) values (963, 'Creamers - 10%', 43.86);
insert into product (id, name, price) values (964, 'Wine - Shiraz South Eastern', 58.15);
insert into product (id, name, price) values (965, 'Canada Dry', 9.45);
insert into product (id, name, price) values (966, 'Bread - Crusty Italian Poly', 39.79);
insert into product (id, name, price) values (967, 'Oranges - Navel, 72', 91.25);
insert into product (id, name, price) values (968, 'Coffee - Decafenated', 54.22);
insert into product (id, name, price) values (969, 'Duck - Fat', 30.8);
insert into product (id, name, price) values (970, 'Lettuce - Escarole', 64.25);
insert into product (id, name, price) values (971, 'Milk - Buttermilk', 93.85);
insert into product (id, name, price) values (972, 'Smoked Tongue', 21.61);
insert into product (id, name, price) values (973, 'Versatainer Nc - 9388', 14.81);
insert into product (id, name, price) values (974, 'Cake - Mini Potato Pancake', 61.81);
insert into product (id, name, price) values (975, 'Cheese - St. Paulin', 49.49);
insert into product (id, name, price) values (976, 'Pumpkin', 54.93);
insert into product (id, name, price) values (977, 'Edible Flower - Mixed', 70.78);
insert into product (id, name, price) values (978, 'Ocean Spray - Kiwi Strawberry', 26.38);
insert into product (id, name, price) values (979, 'Wine - Two Oceans Cabernet', 46.78);
insert into product (id, name, price) values (980, 'Beef - Rib Roast, Capless', 27.4);
insert into product (id, name, price) values (981, 'Sesame Seed', 27.79);
insert into product (id, name, price) values (982, 'Lobster - Live', 63.27);
insert into product (id, name, price) values (983, 'Eggwhite Frozen', 21.84);
insert into product (id, name, price) values (984, 'Tomatoes - Diced, Canned', 33.18);
insert into product (id, name, price) values (985, 'Beef - Tongue, Fresh', 96.02);
insert into product (id, name, price) values (986, 'Wine - Mas Chicet Rose, Vintage', 33.68);
insert into product (id, name, price) values (987, 'Muffin Mix - Blueberry', 72.58);
insert into product (id, name, price) values (988, 'Cookie - Dough Variety', 4.23);
insert into product (id, name, price) values (989, 'Easy Off Oven Cleaner', 51.56);
insert into product (id, name, price) values (990, 'Veal - Loin', 15.47);
insert into product (id, name, price) values (991, 'Chicken - Base', 79.98);
insert into product (id, name, price) values (992, 'Steampan - Lid For Half Size', 63.62);
insert into product (id, name, price) values (993, 'Juice - Grapefruit, 341 Ml', 7.05);
insert into product (id, name, price) values (994, 'Sage - Fresh', 79.74);
insert into product (id, name, price) values (995, 'Juice - Lagoon Mango', 93.66);
insert into product (id, name, price) values (996, 'Brownies - Two Bite, Chocolate', 56.22);
insert into product (id, name, price) values (997, 'Cake - Mini Potato Pancake', 29.8);
insert into product (id, name, price) values (998, 'Shichimi Togarashi Peppeers', 94.45);
insert into product (id, name, price) values (999, 'Tomatoes - Grape', 20.17);
insert into product (id, name, price) values (1000, 'Longos - Penne With Pesto', 72.79);
